# DDL
DROP CONTINUOUS QUERY cq_kwh ON powerwall
DROP CONTINUOUS QUERY cq_grid ON powerwall
DROP CONTINUOUS QUERY cq_alerts ON powerwall
DROP CONTINUOUS QUERY cq_daily ON powerwall
DROP CONTINUOUS QUERY cq_monthly ON powerwall
DROP CONTINUOUS QUERY cq_autogen ON powerwall
DROP CONTINUOUS QUERY cq_autogen_current ON powerwall
DROP CONTINUOUS QUERY cq_autogen_voltage ON powerwall
DROP CONTINUOUS QUERY cq_pw_temps ON powerwall
DROP CONTINUOUS QUERY cq_pw_tempsb ON powerwall
DROP CONTINUOUS QUERY cq_strings0 ON powerwall
DROP CONTINUOUS QUERY cq_strings1 ON powerwall
DROP CONTINUOUS QUERY cq_inverters0 ON powerwall
DROP CONTINUOUS QUERY cq_inverters1 ON powerwall
DROP CONTINUOUS QUERY cq_vitals1 ON powerwall
DROP CONTINUOUS QUERY cq_vitals1b ON powerwall
DROP CONTINUOUS QUERY cq_vitals2 ON powerwall
DROP CONTINUOUS QUERY cq_vitals3 ON powerwall
DROP CONTINUOUS QUERY cq_vitals4 ON powerwall
DROP CONTINUOUS QUERY cq_vitals4b ON powerwall
DROP CONTINUOUS QUERY cq_vitals5 ON powerwall
DROP CONTINUOUS QUERY cq_vitals5b ON powerwall
DROP CONTINUOUS QUERY cq_vitals6 ON powerwall
DROP CONTINUOUS QUERY cq_vitals7 ON powerwall
DROP CONTINUOUS QUERY cq_vitals8 ON powerwall
DROP CONTINUOUS QUERY cq_vitals9 ON powerwall
DROP CONTINUOUS QUERY cq_vitals10 ON powerwall
DROP CONTINUOUS QUERY cq_vitals11 ON powerwall
DROP CONTINUOUS QUERY cq_vitals12 ON powerwall
DROP CONTINUOUS QUERY cq_pod1 ON powerwall
DROP CONTINUOUS QUERY cq_pod1b ON powerwall
DROP CONTINUOUS QUERY cq_pod2 ON powerwall
DROP CONTINUOUS QUERY cq_pod2b ON powerwall
DROP CONTINUOUS QUERY cq_pod3 ON powerwall
DROP CONTINUOUS QUERY cq_pod4 ON powerwall
DROP CONTINUOUS QUERY cq_fans ON powerwall
